-- SmartFinance Database Schema
-- Demonstrates all 10 DBMS Modules

-- MODULE I: Entity-Relationship Modeling
-- Users table - single user entity for this app
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Categories table - lookup table for transaction categories
CREATE TABLE IF NOT EXISTS categories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    type TEXT CHECK(type IN ('income', 'expense')) NOT NULL,
    icon TEXT,
    color TEXT
);

-- MODULE II: Relational Data Model
-- Transactions table - main entity with foreign keys
CREATE TABLE IF NOT EXISTS transactions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    category_id INTEGER NOT NULL,
    amount REAL NOT NULL,
    description TEXT,
    date DATE NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

-- Budgets table - tracks monthly budget limits per category
CREATE TABLE IF NOT EXISTS budgets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    category_id INTEGER NOT NULL,
    amount REAL NOT NULL,
    month TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (category_id) REFERENCES categories(id),
    UNIQUE(user_id, category_id, month)
);

-- Recurring transactions for subscriptions and regular income
CREATE TABLE IF NOT EXISTS recurring_transactions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    category_id INTEGER NOT NULL,
    amount REAL NOT NULL,
    description TEXT,
    frequency TEXT CHECK(frequency IN ('daily', 'weekly', 'monthly')),
    next_due_date DATE NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

-- User settings for the redesigned dashboard experience
CREATE TABLE IF NOT EXISTS user_settings (
    user_id INTEGER PRIMARY KEY,
    theme TEXT CHECK(theme IN ('light', 'dark', 'system')) DEFAULT 'dark',
    currency TEXT DEFAULT 'INR',
    monthly_goal REAL DEFAULT 1000,
    alert_threshold INTEGER DEFAULT 80,
    ai_advisor_enabled INTEGER DEFAULT 1,
    receipt_scan_enabled INTEGER DEFAULT 1,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Persistent activity notifications generated by app actions
CREATE TABLE IF NOT EXISTS notifications (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    is_read INTEGER DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Support requests from the support center screen
CREATE TABLE IF NOT EXISTS support_requests (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    subject TEXT NOT NULL,
    category TEXT DEFAULT 'General',
    message TEXT NOT NULL,
    status TEXT DEFAULT 'open',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- MODULE III: SQL Data Types and Constraints
-- Indexes for performance optimization
CREATE INDEX IF NOT EXISTS idx_transactions_date ON transactions(date);
CREATE INDEX IF NOT EXISTS idx_transactions_category ON transactions(category_id);
CREATE INDEX IF NOT EXISTS idx_transactions_user ON transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON notifications(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_support_user_created ON support_requests(user_id, created_at);

-- MODULE IV: Relational Algebra and Set Operations
-- MODULE V: Aggregation with GROUP BY and HAVING
-- MODULE VI: Subqueries and Nested Queries

-- View: Monthly Summary - demonstrates GROUP BY, CASE, and aggregation
CREATE VIEW IF NOT EXISTS monthly_summary AS
SELECT
    strftime('%Y-%m', date) as month,
    SUM(CASE WHEN c.type = 'income' THEN t.amount ELSE 0 END) as total_income,
    SUM(CASE WHEN c.type = 'expense' THEN t.amount ELSE 0 END) as total_expense,
    SUM(CASE WHEN c.type = 'income' THEN t.amount ELSE -t.amount END) as savings
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE t.user_id = 1
GROUP BY strftime('%Y-%m', date);

-- View: Budget Health - demonstrates JOIN, HAVING, and CASE for status
DROP VIEW IF EXISTS budget_health;
CREATE VIEW budget_health AS
SELECT
    b.id as budget_id,
    b.category_id,
    c.name as category_name,
    c.icon as category_icon,
    c.color as category_color,
    b.amount as budget_amount,
    b.month,
    COALESCE(SUM(t.amount), 0) as spent_amount,
    b.amount - COALESCE(SUM(t.amount), 0) as remaining_amount,
    CASE
        WHEN COALESCE(SUM(t.amount), 0) >= b.amount THEN 'exceeded'
        WHEN (b.amount - COALESCE(SUM(t.amount), 0)) / b.amount <= 0.2 THEN 'critical'
        WHEN (b.amount - COALESCE(SUM(t.amount), 0)) / b.amount <= 0.5 THEN 'warning'
        ELSE 'healthy'
    END as status
FROM budgets b
JOIN categories c ON b.category_id = c.id
LEFT JOIN transactions t ON b.category_id = t.category_id
    AND strftime('%Y-%m', t.date) = b.month
    AND t.user_id = b.user_id
WHERE b.user_id = 1
GROUP BY b.id, b.category_id, c.name, c.icon, c.color, b.amount, b.month;

-- View: Top Categories - demonstrates GROUP BY, ORDER BY, LIMIT
DROP VIEW IF EXISTS top_categories;
CREATE VIEW top_categories AS
SELECT
    c.id as category_id,
    c.name as category_name,
    c.icon as category_icon,
    c.color as category_color,
    c.type as category_type,
    SUM(t.amount) as total_amount,
    COUNT(*) as transaction_count,
    strftime('%Y-%m', t.date) as month
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE t.user_id = 1
    AND c.type = 'expense'
GROUP BY c.id, c.name, c.icon, c.color, c.type, month
ORDER BY total_amount DESC;

-- MODULE VII: Normalization (3NF is already achieved with normalized tables)
-- MODULE VIII: Transaction Management
-- MODULE IX: Concurrency Control
-- MODULE X: Query Optimization (indexes created above)
